"""attributes and options

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-09 12:50:07.931634

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('frontend_input', sa.String(length=64), nullable=False),
    sa.Column('declared_scope', sa.String(length=16), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('attribute_set_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    op.create_index(op.f('ix_attribute_tenant_id'), 'attribute', ['tenant_id'], unique=False)
    op.create_table('attribute_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('attribute_code', sa.String(length=255), nullable=False),
    sa.Column('magento_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'attribute_code', 'magento_option_id')
    )
    op.create_index(op.f('ix_attribute_option_attribute_code'), 'attribute_option', ['attribute_code'], unique=False)
    op.create_index(op.f('ix_attribute_option_tenant_id'), 'attribute_option', ['tenant_id'], unique=False)
    op.create_table('attribute_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('magento_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'magento_id')
    )
    op.create_index(op.f('ix_attribute_set_tenant_id'), 'attribute_set', ['tenant_id'], unique=False)
    op.create_table('attribute_option_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_row_id', sa.Integer(), nullable=False),
    sa.Column('store_view_magento_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['option_row_id'], ['attribute_option.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_row_id', 'store_view_magento_id')
    )
    op.create_index(op.f('ix_attribute_option_label_option_row_id'), 'attribute_option_label', ['option_row_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attribute_option_label_option_row_id'), table_name='attribute_option_label')
    op.drop_table('attribute_option_label')
    op.drop_index(op.f('ix_attribute_set_tenant_id'), table_name='attribute_set')
    op.drop_table('attribute_set')
    op.drop_index(op.f('ix_attribute_option_tenant_id'), table_name='attribute_option')
    op.drop_index(op.f('ix_attribute_option_attribute_code'), table_name='attribute_option')
    op.drop_table('attribute_option')
    op.drop_index(op.f('ix_attribute_tenant_id'), table_name='attribute')
    op.drop_table('attribute')
    # ### end Alembic commands ###
