"""product records

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-09 12:55:00.450560

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('store_view_magento_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('mpn', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('gtin', sa.String(length=64), nullable=True),
    sa.Column('variant_key', sa.String(length=255), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('scope_provenance', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('magento_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mirrored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku', 'store_view_magento_id')
    )
    op.create_index(op.f('ix_product_record_content_hash'), 'product_record', ['content_hash'], unique=False)
    op.create_index(op.f('ix_product_record_sku'), 'product_record', ['sku'], unique=False)
    op.create_index(op.f('ix_product_record_store_view_magento_id'), 'product_record', ['store_view_magento_id'], unique=False)
    op.create_index(op.f('ix_product_record_tenant_id'), 'product_record', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_record_tenant_id'), table_name='product_record')
    op.drop_index(op.f('ix_product_record_store_view_magento_id'), table_name='product_record')
    op.drop_index(op.f('ix_product_record_sku'), table_name='product_record')
    op.drop_index(op.f('ix_product_record_content_hash'), table_name='product_record')
    op.drop_table('product_record')
    # ### end Alembic commands ###
