"""categories

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-09 13:03:23.939985

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('magento_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.JSON(), nullable=False),
    sa.Column('default_name', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'magento_id')
    )
    op.create_index(op.f('ix_category_tenant_id'), 'category', ['tenant_id'], unique=False)
    op.create_table('category_store_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('category_magento_id', sa.Integer(), nullable=False),
    sa.Column('store_view_magento_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'category_magento_id', 'store_view_magento_id')
    )
    op.create_index(op.f('ix_category_store_state_category_magento_id'), 'category_store_state', ['category_magento_id'], unique=False)
    op.create_index(op.f('ix_category_store_state_tenant_id'), 'category_store_state', ['tenant_id'], unique=False)
    op.create_table('product_category_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('category_magento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku', 'category_magento_id')
    )
    op.create_index(op.f('ix_product_category_assignment_category_magento_id'), 'product_category_assignment', ['category_magento_id'], unique=False)
    op.create_index(op.f('ix_product_category_assignment_sku'), 'product_category_assignment', ['sku'], unique=False)
    op.create_index(op.f('ix_product_category_assignment_tenant_id'), 'product_category_assignment', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_category_assignment_tenant_id'), table_name='product_category_assignment')
    op.drop_index(op.f('ix_product_category_assignment_sku'), table_name='product_category_assignment')
    op.drop_index(op.f('ix_product_category_assignment_category_magento_id'), table_name='product_category_assignment')
    op.drop_table('product_category_assignment')
    op.drop_index(op.f('ix_category_store_state_tenant_id'), table_name='category_store_state')
    op.drop_index(op.f('ix_category_store_state_category_magento_id'), table_name='category_store_state')
    op.drop_table('category_store_state')
    op.drop_index(op.f('ix_category_tenant_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
