"""product signals

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-09 13:21:23.996954

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('store_view_magento_id', sa.Integer(), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('salable_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('physical_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('uses_msi', sa.Boolean(), nullable=False),
    sa.Column('margin', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('search_demand', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku', 'store_view_magento_id')
    )
    op.create_index(op.f('ix_product_signal_sku'), 'product_signal', ['sku'], unique=False)
    op.create_index(op.f('ix_product_signal_store_view_magento_id'), 'product_signal', ['store_view_magento_id'], unique=False)
    op.create_index(op.f('ix_product_signal_tenant_id'), 'product_signal', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_signal_tenant_id'), table_name='product_signal')
    op.drop_index(op.f('ix_product_signal_store_view_magento_id'), table_name='product_signal')
    op.drop_index(op.f('ix_product_signal_sku'), table_name='product_signal')
    op.drop_table('product_signal')
    # ### end Alembic commands ###
